"""add length to operations

Revision ID: 4196588652e6
Revises: 915cc3f0b13b
Create Date: 2026-04-28 23:19:10.658781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4196588652e6"
down_revision: Union[str, Sequence[str], None] = "915cc3f0b13b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operations", sa.Column("length", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operations", "length")
    # ### end Alembic commands ###
