"""increase char column length

Revision ID: 915cc3f0b13b
Revises: a1b2c3d4e5f6
Create Date: 2026-04-28 22:58:52.738684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "915cc3f0b13b"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operations",
        "char",
        existing_type=sa.VARCHAR(length=1),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operations",
        "char",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
